import '../styles/modern-normalize.css'
import '../styles/style.css'
import '../styles/components/header.css'
import '../styles/components/profile.css'
import '../styles/components/skills.css'
import '../styles/components/projects.css'
import '../styles/components/contact.css'
import '../styles/utils.css'